export const TANGO_STREAM_TOKEN_TTL_S = 10;

export const TANGO_SESSION_TOKEN_TTL_S = 60 * 60;

export const TANGO_STREAM_TOKEN_REFRESH_MS = (TANGO_STREAM_TOKEN_TTL_S / 2) * 1000;
export const TANGO_SESSION_REFRESH_MS = (TANGO_SESSION_TOKEN_TTL_S / 2) * 1000;
